/*
* ====================================================================
* CHÚ THÍCH CẤU TRÚC DỮ LIỆU NGUYÊN TỐ
* ====================================================================
*
* Mỗi nguyên tố trong đối tượng `periodicTableData` được định nghĩa
* bằng Ký hiệu Hóa học (ví dụ: 'H', 'Fe', 'Au') làm "key".
* Mỗi "key" trỏ đến một đối tượng (object) chứa các thuộc tính sau:
*
* - number: (Số) Số hiệu nguyên tử.
* - symbol: (Chuỗi) Ký hiệu hóa học (ví dụ: "H").
* - name: (Chuỗi) Tên tiếng Việt thông dụng (ví dụ: "Hydro", "Sắt").
* - nameEN: (Chuỗi) Tên quốc tế/tiếng Anh (ví dụ: "Hydrogen", "Iron").
* - summary: (Chuỗi) Một câu tóm tắt thú vị về nguyên tố, hiển thị trong sidebar.
*
* - x: (Số) Vị trí cột (grid-column) để hiển thị trên bảng tuần hoàn (từ 1 đến 18).
* - y: (Số) Vị trí hàng (grid-row) để hiển thị trên bảng tuần hoàn (từ 1 đến 10).
* - categoryClass: (Chuỗi) Tên lớp CSS dùng để định dạng màu sắc
* (ví dụ: 'alkali-metal', 'noble-gas', 'unknown').
*
* - modelSrc: (Chuỗi/null) Đường dẫn (URL) đến tệp mô hình 3D (.glb).
* Nếu là `null`, tab 3D sẽ hiển thị thông báo "không có".
*
* - atomicMass: (Chuỗi) Khối lượng nguyên tử, đơn vị (u).
* (Lưu dưới dạng Chuỗi để giữ nguyên các số 0 ở cuối).
* - density: (Số/null) Khối lượng riêng (g/cm³).
* - meltingPoint: (Số/null) Điểm nóng chảy (đơn vị K - Kelvin).
* - boilingPoint: (Số/null) Điểm sôi (đơn vị K - Kelvin).
* - yearDiscovered: (Chuỗi) Năm phát hiện (ví dụ: "1766" hoặc "Cổ đại").
*
* ====================================================================
*/

// 'alkali-metal': 'Kim loại kiềm',
// 'alkaline-earth-metal': 'Kim loại kiềm thổ',
// 'transition-metal': 'Kim loại chuyển tiếp',
// 'post-transition-metal': 'Kim loại sau chuyển thiếp', 
// 'metalloid': 'Á kim',
// 'reactive-nonmetal': 'Phi kim', 
// 'noble-gas': 'Khí hiếm',
// 'lanthanide': 'Nhóm Lanthanides',
// 'actinide': 'Nhóm Actinides',
// 'unknown': 'Chưa rõ' 

const periodicTableData = {
    "H": {
        "number": 1,
        "symbol": "H",
        "name": "Hydro",
        "nameEN": "Hydrogen",
        "summary": "Nguyên tố phổ biến nhất vũ trụ.",
        "x": 1,
        "y": 1,
        "categoryClass": "reactive-nonmetal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_001_hydrogen/element_001_hydrogen.glb",
        "atomicMass": "1.008",
        "density": 8.988e-05,
        "meltingPoint": 13.99,
        "boilingPoint": 20.271,
        "yearDiscovered": "1766"
    },
    "He": {
        "number": 2,
        "symbol": "He",
        "name": "Heli",
        "nameEN": "Helium",
        "summary": "Khí trơ, nhẹ hơn không khí.",
        "x": 18,
        "y": 1,
        "categoryClass": "noble-gas",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_002_helium/element_002_helium.glb",
        "atomicMass": "4.0026",
        "density": 0.0001785,
        "meltingPoint": null,
        "boilingPoint": 4.22,
        "yearDiscovered": "1895"
    },
    "Li": {
        "number": 3,
        "symbol": "Li",
        "name": "Lithi",
        "nameEN": "Lithium",
        "summary": "Kim loại nhẹ nhất, dùng trong pin sạc.",
        "x": 1,
        "y": 2,
        "categoryClass": "alkali-metal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_003_lithium/element_003_lithium.glb",
        "atomicMass": "6.94",
        "density": 0.534,
        "meltingPoint": 453.65,
        "boilingPoint": 1615,
        "yearDiscovered": "1817"
    },
    "Be": {
        "number": 4,
        "symbol": "Be",
        "name": "Beryli",
        "nameEN": "Beryllium",
        "summary": "Kim loại kiềm thổ, nhẹ và cứng.",
        "x": 2,
        "y": 2,
        "categoryClass": "alkaline-earth-metal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_004_beryllium/element_004_beryllium.glb",
        "atomicMass": "9.0122",
        "density": 1.85,
        "meltingPoint": 1560,
        "boilingPoint": 2742,
        "yearDiscovered": "1798"
    },
    "B": {
        "number": 5,
        "symbol": "B",
        "name": "Bo",
        "nameEN": "Boron",
        "summary": "Á kim, dùng trong chất bán dẫn.",
        "x": 13,
        "y": 2,
        "categoryClass": "metalloid",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_005_boron/element_005_boron.glb",
        "atomicMass": "10.81",
        "density": 2.34,
        "meltingPoint": 2349,
        "boilingPoint": 4200,
        "yearDiscovered": "1808"
    },
    "C": {
        "number": 6,
        "symbol": "C",
        "name": "Carbon",
        "nameEN": "Carbon",
        "summary": "Nền tảng của sự sống hữu cơ.",
        "x": 14,
        "y": 2,
        "categoryClass": "reactive-nonmetal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_006_carbon/element_006_carbon.glb",
        "atomicMass": "12.011",
        "density": 2.267,
        "meltingPoint": 3800,
        "boilingPoint": 5100,
        "yearDiscovered": "Cổ đại"
    },
    "N": {
        "number": 7,
        "symbol": "N",
        "name": "Nitơ",
        "nameEN": "Nitrogen",
        "summary": "Thành phần chính của khí quyển.",
        "x": 15,
        "y": 2,
        "categoryClass": "reactive-nonmetal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_007_nitrogen/element_007_nitrogen.glb",
        "atomicMass": "14.007",
        "density": 0.0012506,
        "meltingPoint": 63.15,
        "boilingPoint": 77.355,
        "yearDiscovered": "1772"
    },
    "O": {
        "number": 8,
        "symbol": "O",
        "name": "Oxy",
        "nameEN": "Oxygen",
        "summary": "Cần thiết cho sự hô hấp.",
        "x": 16,
        "y": 2,
        "categoryClass": "reactive-nonmetal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_008_oxygen/element_008_oxygen.glb",
        "atomicMass": "15.999",
        "density": 0.001429,
        "meltingPoint": 54.36,
        "boilingPoint": 90.188,
        "yearDiscovered": "1774"
    },
    "F": {
        "number": 9,
        "symbol": "F",
        "name": "Flo",
        "nameEN": "Fluorine",
        "summary": "Halogen hoạt động mạnh nhất.",
        "x": 17,
        "y": 2,
        "categoryClass": "reactive-nonmetal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_009_fluorine/element_009_fluorine.glb",
        "atomicMass": "18.998",
        "density": 0.001696,
        "meltingPoint": 53.48,
        "boilingPoint": 85.03,
        "yearDiscovered": "1886"
    },
    "Ne": {
        "number": 10,
        "symbol": "Ne",
        "name": "Neon",
        "nameEN": "Neon",
        "summary": "Khí hiếm, dùng trong đèn neon.",
        "x": 18,
        "y": 2,
        "categoryClass": "noble-gas",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_010_neon/element_010_neon.glb",
        "atomicMass": "20.180",
        "density": 0.0009002,
        "meltingPoint": 24.56,
        "boilingPoint": 27.07,
        "yearDiscovered": "1898"
    },
    "Na": {
        "number": 11,
        "symbol": "Na",
        "name": "Natri",
        "nameEN": "Sodium",
        "summary": "Kim loại kiềm, phản ứng mạnh với nước.",
        "x": 1,
        "y": 3,
        "categoryClass": "alkali-metal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_011_sodium/element_011_sodium.glb",
        "atomicMass": "22.990",
        "density": 0.971,
        "meltingPoint": 370.944,
        "boilingPoint": 1156,
        "yearDiscovered": "1807"
    },
    "Mg": {
        "number": 12,
        "symbol": "Mg",
        "name": "Magie",
        "nameEN": "Magnesium",
        "summary": "Kim loại kiềm thổ, cháy sáng.",
        "x": 2,
        "y": 3,
        "categoryClass": "alkaline-earth-metal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_012_magnesium/element_012_magnesium.glb",
        "atomicMass": "24.305",
        "density": 1.738,
        "meltingPoint": 923,
        "boilingPoint": 1363,
        "yearDiscovered": "1755"
    },
    "Al": {
        "number": 13,
        "symbol": "Al",
        "name": "Nhôm",
        "nameEN": "Aluminium",
        "summary": "Kim loại nhẹ, bền, phổ biến.",
        "x": 13,
        "y": 3,
        "categoryClass": "post-transition-metal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_013_aluminium/element_013_aluminium.glb",
        "atomicMass": "26.982",
        "density": 2.698,
        "meltingPoint": 933.47,
        "boilingPoint": 2792,
        "yearDiscovered": "1825"
    },
    "Si": {
        "number": 14,
        "symbol": "Si",
        "name": "Silic",
        "nameEN": "Silicon",
        "summary": "Á kim, nền tảng của vi mạch.",
        "x": 14,
        "y": 3,
        "categoryClass": "metalloid",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_014_silicon/element_014_silicon.glb",
        "atomicMass": "28.085",
        "density": 2.3296,
        "meltingPoint": 1687,
        "boilingPoint": 3538,
        "yearDiscovered": "1824"
    },
    "P": {
        "number": 15,
        "symbol": "P",
        "name": "Phospho",
        "nameEN": "Phosphorus",
        "summary": "Quan trọng cho ATP và DNA.",
        "x": 15,
        "y": 3,
        "categoryClass": "reactive-nonmetal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_015_phosphorus/element_015_phosphorus.glb",
        "atomicMass": "30.974",
        "density": 1.82,
        "meltingPoint": 317.3,
        "boilingPoint": 553.6,
        "yearDiscovered": "1669"
    },
    "S": {
        "number": 16,
        "symbol": "S",
        "name": "Lưu huỳnh",
        "nameEN": "Sulfur",
        "summary": "Phi kim màu vàng, có mùi đặc trưng.",
        "x": 16,
        "y": 3,
        "categoryClass": "reactive-nonmetal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_016_sulfur/element_016_sulfur.glb",
        "atomicMass": "32.06",
        "density": 2.067,
        "meltingPoint": 388.36,
        "boilingPoint": 717.8,
        "yearDiscovered": "Cổ đại"
    },
    "Cl": {
        "number": 17,
        "symbol": "Cl",
        "name": "Clo",
        "nameEN": "Chlorine",
        "summary": "Halogen, chất khử trùng mạnh.",
        "x": 17,
        "y": 3,
        "categoryClass": "reactive-nonmetal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_017_chlorine/element_017_chlorine.glb",
        "atomicMass": "35.45",
        "density": 0.003214,
        "meltingPoint": 171.6,
        "boilingPoint": 239.11,
        "yearDiscovered": "1774"
    },
    "Ar": {
        "number": 18,
        "symbol": "Ar",
        "name": "Argon",
        "nameEN": "Argon",
        "summary": "Khí hiếm, dùng trong bóng đèn.",
        "x": 18,
        "y": 3,
        "categoryClass": "noble-gas",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_018_argon/element_018_argon.glb",
        "atomicMass": "39.948",
        "density": 0.0017837,
        "meltingPoint": 83.81,
        "boilingPoint": 87.302,
        "yearDiscovered": "1894"
    },
    "K": {
        "number": 19,
        "symbol": "K",
        "name": "Kali",
        "nameEN": "Potassium",
        "summary": "Kim loại kiềm, quan trọng cho tế bào.",
        "x": 1,
        "y": 4,
        "categoryClass": "alkali-metal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_019_potassium/element_019_potassium.glb",
        "atomicMass": "39.098",
        "density": 0.862,
        "meltingPoint": 336.7,
        "boilingPoint": 1032,
        "yearDiscovered": "1807"
    },
    "Ca": {
        "number": 20,
        "symbol": "Ca",
        "name": "Canxi",
        "nameEN": "Calcium",
        "summary": "Kim loại kiềm thổ, thành phần của xương.",
        "x": 2,
        "y": 4,
        "categoryClass": "alkaline-earth-metal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_020_calcium/element_020_calcium.glb",
        "atomicMass": "40.078",
        "density": 1.54,
        "meltingPoint": 1115,
        "boilingPoint": 1757,
        "yearDiscovered": "1808"
    },
    "Sc": {
        "number": 21,
        "symbol": "Sc",
        "name": "Scandi",
        "nameEN": "Scandium",
        "summary": "Kim loại chuyển tiếp, dùng trong hợp kim.",
        "x": 3,
        "y": 4,
        "categoryClass": "transition-metal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_021_scandium/element_021_scandium.glb",
        "atomicMass": "44.956",
        "density": 2.989,
        "meltingPoint": 1814,
        "boilingPoint": 3109,
        "yearDiscovered": "1879"
    },
    "Ti": {
        "number": 22,
        "symbol": "Ti",
        "name": "Titan",
        "nameEN": "Titanium",
        "summary": "Kim loại nhẹ, cứng, chống ăn mòn.",
        "x": 4,
        "y": 4,
        "categoryClass": "transition-metal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_022_titanium/element_022_titanium.glb",
        "atomicMass": "47.867",
        "density": 4.54,
        "meltingPoint": 1941,
        "boilingPoint": 3560,
        "yearDiscovered": "1791"
    },
    "V": {
        "number": 23,
        "symbol": "V",
        "name": "Vanadi",
        "nameEN": "Vanadium",
        "summary": "Kim loại chuyển tiếp, làm cứng thép.",
        "x": 5,
        "y": 4,
        "categoryClass": "transition-metal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_023_vanadium/element_023_vanadium.glb",
        "atomicMass": "50.942",
        "density": 6.11,
        "meltingPoint": 2183,
        "boilingPoint": 3680,
        "yearDiscovered": "1801"
    },
    "Cr": {
        "number": 24,
        "symbol": "Cr",
        "name": "Crom",
        "nameEN": "Chromium",
        "summary": "Kim loại chuyển tiếp, dùng để mạ.",
        "x": 6,
        "y": 4,
        "categoryClass": "transition-metal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_024_chromium/element_024_chromium.glb",
        "atomicMass": "51.996",
        "density": 7.15,
        "meltingPoint": 2180,
        "boilingPoint": 2944,
        "yearDiscovered": "1797"
    },
    "Mn": {
        "number": 25,
        "symbol": "Mn",
        "name": "Mangan",
        "nameEN": "Manganese",
        "summary": "Kim loại chuyển tiếp, dùng trong thép.",
        "x": 7,
        "y": 4,
        "categoryClass": "transition-metal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_025_manganese/element_025_manganese.glb",
        "atomicMass": "54.938",
        "density": 7.44,
        "meltingPoint": 1519,
        "boilingPoint": 2334,
        "yearDiscovered": "1774"
    },
    "Fe": {
        "number": 26,
        "symbol": "Fe",
        "name": "Sắt",
        "nameEN": "Iron",
        "summary": "Kim loại chuyển tiếp, quan trọng nhất.",
        "x": 8,
        "y": 4,
        "categoryClass": "transition-metal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_026_iron/element_026_iron.glb",
        "atomicMass": "55.845",
        "density": 7.874,
        "meltingPoint": 1811,
        "boilingPoint": 3134,
        "yearDiscovered": "Cổ đại"
    },
    "Co": {
        "number": 27,
        "symbol": "Co",
        "name": "Coban",
        "nameEN": "Cobalt",
        "summary": "Kim loại chuyển tiếp, có từ tính.",
        "x": 9,
        "y": 4,
        "categoryClass": "transition-metal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_027_cobalt/element_027_cobalt.glb",
        "atomicMass": "58.933",
        "density": 8.86,
        "meltingPoint": 1768,
        "boilingPoint": 3200,
        "yearDiscovered": "1735"
    },
    "Ni": {
        "number": 28,
        "symbol": "Ni",
        "name": "Niken",
        "nameEN": "Nickel",
        "summary": "Kim loại chuyển tiếp, dùng trong pin.",
        "x": 10,
        "y": 4,
        "categoryClass": "transition-metal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_028_nickel/element_028_nickel.glb",
        "atomicMass": "58.693",
        "density": 8.912,
        "meltingPoint": 1728,
        "boilingPoint": 3186,
        "yearDiscovered": "1751"
    },
    "Cu": {
        "number": 29,
        "symbol": "Cu",
        "name": "Đồng",
        "nameEN": "Copper",
        "summary": "Kim loại chuyển tiếp, dẫn điện tốt.",
        "x": 11,
        "y": 4,
        "categoryClass": "transition-metal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_029_copper/element_029_copper.glb",
        "atomicMass": "63.546",
        "density": 8.96,
        "meltingPoint": 1357.77,
        "boilingPoint": 2835,
        "yearDiscovered": "Cổ đại"
    },
    "Zn": {
        "number": 30,
        "symbol": "Zn",
        "name": "Kẽm",
        "nameEN": "Zinc",
        "summary": "Kim loại chuyển tiếp, chống gỉ (mạ).",
        "x": 12,
        "y": 4,
        "categoryClass": "transition-metal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_030_zinc/element_030_zinc.glb",
        "atomicMass": "65.38",
        "density": 7.134,
        "meltingPoint": 692.68,
        "boilingPoint": 1180,
        "yearDiscovered": "Cổ đại"
    },
    "Ga": {
        "number": 31,
        "symbol": "Ga",
        "name": "Gali",
        "nameEN": "Gallium",
        "summary": "Kim loại yếu, nóng chảy ở nhiệt độ thấp.",
        "x": 13,
        "y": 4,
        "categoryClass": "post-transition-metal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_031_gallium/element_031_gallium.glb",
        "atomicMass": "69.723",
        "density": 5.907,
        "meltingPoint": 302.9146,
        "boilingPoint": 2673,
        "yearDiscovered": "1875"
    },
    "Ge": {
        "number": 32,
        "symbol": "Ge",
        "name": "Gemani",
        "nameEN": "Germanium",
        "summary": "Á kim, chất bán dẫn.",
        "x": 14,
        "y": 4,
        "categoryClass": "metalloid",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_032_germanium/element_032_germanium.glb",
        "atomicMass": "72.630",
        "density": 5.323,
        "meltingPoint": 1211.4,
        "boilingPoint": 3106,
        "yearDiscovered": "1886"
    },
    "As": {
        "number": 33,
        "symbol": "As",
        "name": "Asen",
        "nameEN": "Arsenic",
        "summary": "Á kim, được biết đến là chất độc.",
        "x": 15,
        "y": 4,
        "categoryClass": "metalloid",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_033_arsenic/element_033_arsenic.glb",
        "atomicMass": "74.922",
        "density": 5.776,
        "meltingPoint": null,
        "boilingPoint": 887,
        "yearDiscovered": "Cổ đại"
    },
    "Se": {
        "number": 34,
        "symbol": "Se",
        "name": "Selen",
        "nameEN": "Selenium",
        "summary": "Phi kim, dùng trong pin mặt trời.",
        "x": 16,
        "y": 4,
        "categoryClass": "reactive-nonmetal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_034_selenium/element_034_selenium.glb",
        "atomicMass": "78.971",
        "density": 4.809,
        "meltingPoint": 494,
        "boilingPoint": 958,
        "yearDiscovered": "1817"
    },
    "Br": {
        "number": 35,
        "symbol": "Br",
        "name": "Brom",
        "nameEN": "Bromine",
        "summary": "Halogen, chất lỏng ở nhiệt độ phòng.",
        "x": 17,
        "y": 4,
        "categoryClass": "reactive-nonmetal",
        "modelSrc": "https://storage.googleapis.com/search-ar-edu/periodic-table/element_035_bromine/element_035_bromine.glb",
        "atomicMass": "79.904",
        "density": 3.122,
        "meltingPoint": 265.8,
        "boilingPoint": 332,
        "yearDiscovered": "1826"
    },
    "Kr": {
        "number": 36,
        "symbol": "Kr",
        "name": "Krypton",
        "nameEN": "Krypton",
        "summary": "Khí hiếm, dùng trong đèn laser.",
        "x": 18,
        "y": 4,
        "categoryClass": "noble-gas",
        "modelSrc": null,
        "atomicMass": "83.798",
        "density": 0.003733,
        "meltingPoint": 115.78,
        "boilingPoint": 119.93,
        "yearDiscovered": "1898"
    },
    "Rb": {
        "number": 37,
        "symbol": "Rb",
        "name": "Rubidi",
        "nameEN": "Rubidium",
        "summary": "Kim loại kiềm, dùng trong đồng hồ nguyên tử.",
        "x": 1,
        "y": 5,
        "categoryClass": "alkali-metal",
        "modelSrc": null,
        "atomicMass": "85.468",
        "density": 1.532,
        "meltingPoint": 312.45,
        "boilingPoint": 961,
        "yearDiscovered": "1861"
    },
    "Sr": {
        "number": 38,
        "symbol": "Sr",
        "name": "Stronti",
        "nameEN": "Strontium",
        "summary": "Kim loại kiềm thổ, dùng trong pháo hoa.",
        "x": 2,
        "y": 5,
        "categoryClass": "alkaline-earth-metal",
        "modelSrc": null,
        "atomicMass": "87.62",
        "density": 2.64,
        "meltingPoint": 1050,
        "boilingPoint": 1655,
        "yearDiscovered": "1790"
    },
    "Y": {
        "number": 39,
        "symbol": "Y",
        "name": "Ytri",
        "nameEN": "Yttrium",
        "summary": "Kim loại chuyển tiếp, dùng trong LED.",
        "x": 3,
        "y": 5,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "88.906",
        "density": 4.469,
        "meltingPoint": 1799,
        "boilingPoint": 3609,
        "yearDiscovered": "1794"
    },
    "Zr": {
        "number": 40,
        "symbol": "Zr",
        "name": "Zirconi",
        "nameEN": "Zirconium",
        "summary": "Kim loại chuyển tiếp, chống ăn mòn cao.",
        "x": 4,
        "y": 5,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "91.224",
        "density": 6.506,
        "meltingPoint": 2128,
        "boilingPoint": 4682,
        "yearDiscovered": "1789"
    },
    "Nb": {
        "number": 41,
        "symbol": "Nb",
        "name": "Niobi",
        "nameEN": "Niobium",
        "summary": "Kim loại chuyển tiếp, dùng trong siêu hợp kim.",
        "x": 5,
        "y": 5,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "92.906",
        "density": 8.57,
        "meltingPoint": 2750,
        "boilingPoint": 5017,
        "yearDiscovered": "1801"
    },
    "Mo": {
        "number": 42,
        "symbol": "Mo",
        "name": "Molybden",
        "nameEN": "Molybdenum",
        "summary": "Kim loại chuyển tiếp, làm cứng thép.",
        "x": 6,
        "y": 5,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "95.96",
        "density": 10.22,
        "meltingPoint": 2896,
        "boilingPoint": 4912,
        "yearDiscovered": "1781"
    },
    "Tc": {
        "number": 43,
        "symbol": "Tc",
        "name": "Techneti",
        "nameEN": "Technetium",
        "summary": "Nguyên tố phóng xạ nhân tạo đầu tiên.",
        "x": 7,
        "y": 5,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "(98)",
        "density": 11.5,
        "meltingPoint": 2430,
        "boilingPoint": 4538,
        "yearDiscovered": "1937"
    },
    "Ru": {
        "number": 44,
        "symbol": "Ru",
        "name": "Rutheni",
        "nameEN": "Ruthenium",
        "summary": "Kim loại chuyển tiếp, dùng làm chất xúc tác.",
        "x": 8,
        "y": 5,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "101.07",
        "density": 12.37,
        "meltingPoint": 2607,
        "boilingPoint": 4423,
        "yearDiscovered": "1844"
    },
    "Rh": {
        "number": 45,
        "symbol": "Rh",
        "name": "Rhodi",
        "nameEN": "Rhodium",
        "summary": "Kim loại quý, dùng mạ trang sức.",
        "x": 9,
        "y": 5,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "102.906",
        "density": 12.41,
        "meltingPoint": 2237,
        "boilingPoint": 3968,
        "yearDiscovered": "1803"
    },
    "Pd": {
        "number": 46,
        "symbol": "Pd",
        "name": "Palladi",
        "nameEN": "Palladium",
        "summary": "Kim loại chuyển tiếp, dùng trong xử lý khí thải.",
        "x": 10,
        "y": 5,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "106.42",
        "density": 12.02,
        "meltingPoint": 1828.05,
        "boilingPoint": 3236,
        "yearDiscovered": "1803"
    },
    "Ag": {
        "number": 47,
        "symbol": "Ag",
        "name": "Bạc",
        "nameEN": "Silver",
        "summary": "Kim loại quý, dẫn điện tốt nhất.",
        "x": 11,
        "y": 5,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "107.868",
        "density": 10.501,
        "meltingPoint": 1234.93,
        "boilingPoint": 2435,
        "yearDiscovered": "Cổ đại"
    },
    "Cd": {
        "number": 48,
        "symbol": "Cd",
        "name": "Cadmi",
        "nameEN": "Cadmium",
        "summary": "Kim loại chuyển tiếp, độc, dùng trong pin.",
        "x": 12,
        "y": 5,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "112.414",
        "density": 8.69,
        "meltingPoint": 594.22,
        "boilingPoint": 1040,
        "yearDiscovered": "1817"
    },
    "In": {
        "number": 49,
        "symbol": "In",
        "name": "Indi",
        "nameEN": "Indium",
        "summary": "Kim loại yếu, dùng trong màn hình LCD.",
        "x": 13,
        "y": 5,
        "categoryClass": "post-transition-metal",
        "modelSrc": null,
        "atomicMass": "114.818",
        "density": 7.31,
        "meltingPoint": 429.7485,
        "boilingPoint": 2345,
        "yearDiscovered": "1863"
    },
    "Sn": {
        "number": 50,
        "symbol": "Sn",
        "name": "Thiếc",
        "nameEN": "Tin",
        "summary": "Kim loại yếu, dùng trong hợp kim hàn.",
        "x": 14,
        "y": 5,
        "categoryClass": "post-transition-metal",
        "modelSrc": null,
        "atomicMass": "118.710",
        "density": 7.287,
        "meltingPoint": 505.08,
        "boilingPoint": 2875,
        "yearDiscovered": "Cổ đại"
    },
    "Sb": {
        "number": 51,
        "symbol": "Sb",
        "name": "Antimon",
        "nameEN": "Antimony",
        "summary": "Á kim, dùng trong chất chống cháy.",
        "x": 15,
        "y": 5,
        "categoryClass": "metalloid",
        "modelSrc": null,
        "atomicMass": "121.760",
        "density": 6.685,
        "meltingPoint": 903.78,
        "boilingPoint": 1860,
        "yearDiscovered": "Cổ đại"
    },
    "Te": {
        "number": 52,
        "symbol": "Te",
        "name": "Tellu",
        "nameEN": "Tellurium",
        "summary": "Á kim, dùng trong hợp kim, bán dẫn.",
        "x": 16,
        "y": 5,
        "categoryClass": "metalloid",
        "modelSrc": null,
        "atomicMass": "127.60",
        "density": 6.232,
        "meltingPoint": 722.66,
        "boilingPoint": 1261,
        "yearDiscovered": "1782"
    },
    "I": {
        "number": 53,
        "symbol": "I",
        "name": "Iod",
        "nameEN": "Iodine",
        "summary": "Halogen, cần thiết cho tuyến giáp.",
        "x": 17,
        "y": 5,
        "categoryClass": "reactive-nonmetal",
        "modelSrc": null,
        "atomicMass": "126.904",
        "density": 4.93,
        "meltingPoint": 386.85,
        "boilingPoint": 457.4,
        "yearDiscovered": "1811"
    },
    "Xe": {
        "number": 54,
        "symbol": "Xe",
        "name": "Xenon",
        "nameEN": "Xenon",
        "summary": "Khí hiếm, dùng trong đèn flash cường độ cao.",
        "x": 18,
        "y": 5,
        "categoryClass": "noble-gas",
        "modelSrc": null,
        "atomicMass": "131.293",
        "density": 0.005887,
        "meltingPoint": 161.4,
        "boilingPoint": 165.051,
        "yearDiscovered": "1898"
    },
    "Cs": {
        "number": 55,
        "symbol": "Cs",
        "name": "Caesi",
        "nameEN": "Caesium",
        "summary": "Kim loại kiềm hoạt động mạnh nhất.",
        "x": 1,
        "y": 6,
        "categoryClass": "alkali-metal",
        "modelSrc": null,
        "atomicMass": "132.905",
        "density": 1.93,
        "meltingPoint": 301.7,
        "boilingPoint": 944,
        "yearDiscovered": "1860"
    },
    "Ba": {
        "number": 56,
        "symbol": "Ba",
        "name": "Bari",
        "nameEN": "Barium",
        "summary": "Kim loại kiềm thổ, dùng trong chụp X-quang.",
        "x": 2,
        "y": 6,
        "categoryClass": "alkaline-earth-metal",
        "modelSrc": null,
        "atomicMass": "137.327",
        "density": 3.62,
        "meltingPoint": 1000,
        "boilingPoint": 2170,
        "yearDiscovered": "1808"
    },
    "La": {
        "number": 57,
        "symbol": "La",
        "name": "Lanthan",
        "nameEN": "Lanthanum",
        "summary": "Nguyên tố đầu tiên của nhóm Lanthan.",
        "x": 3,
        "y": 6,
        "categoryClass": "lanthanide",
        "modelSrc": null,
        "atomicMass": "138.905",
        "density": 6.145,
        "meltingPoint": 1193,
        "boilingPoint": 3737,
        "yearDiscovered": "1839"
    },
    "Hf": {
        "number": 72,
        "symbol": "Hf",
        "name": "Hafni",
        "nameEN": "Hafnium",
        "summary": "Kim loại chuyển tiếp, dùng trong lò phản ứng.",
        "x": 4,
        "y": 6,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "178.49",
        "density": 13.31,
        "meltingPoint": 2506,
        "boilingPoint": 4876,
        "yearDiscovered": "1923"
    },
    "Ta": {
        "number": 73,
        "symbol": "Ta",
        "name": "Tantal",
        "nameEN": "Tantalum",
        "summary": "Kim loại chuyển tiếp, dùng trong tụ điện.",
        "x": 5,
        "y": 6,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "180.948",
        "density": 16.654,
        "meltingPoint": 3290,
        "boilingPoint": 5731,
        "yearDiscovered": "1802"
    },
    "W": {
        "number": 74,
        "symbol": "W",
        "name": "Wolfram",
        "nameEN": "Tungsten",
        "summary": "Kim loại chuyển tiếp, nhiệt độ nóng chảy cao nhất.",
        "x": 6,
        "y": 6,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "183.84",
        "density": 19.25,
        "meltingPoint": 3695,
        "boilingPoint": 5828,
        "yearDiscovered": "1783"
    },
    "Re": {
        "number": 75,
        "symbol": "Re",
        "name": "Rheni",
        "nameEN": "Rhenium",
        "summary": "Kim loại chuyển tiếp, dùng trong động cơ phản lực.",
        "x": 7,
        "y": 6,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "186.207",
        "density": 21.02,
        "meltingPoint": 3459,
        "boilingPoint": 5869,
        "yearDiscovered": "1925"
    },
    "Os": {
        "number": 76,
        "symbol": "Os",
        "name": "Osmi",
        "nameEN": "Osmium",
        "summary": "Kim loại chuyển tiếp, nặng nhất (tỷ trọng).",
        "x": 8,
        "y": 6,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "190.23",
        "density": 22.59,
        "meltingPoint": 3306,
        "boilingPoint": 5285,
        "yearDiscovered": "1803"
    },
    "Ir": {
        "number": 77,
        "symbol": "Ir",
        "name": "Iridi",
        "nameEN": "Iridium",
        "summary": "Kim loại chuyển tiếp, chống ăn mòn cực tốt.",
        "x": 9,
        "y": 6,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "192.217",
        "density": 22.56,
        "meltingPoint": 2719,
        "boilingPoint": 4701,
        "yearDiscovered": "1803"
    },
    "Pt": {
        "number": 78,
        "symbol": "Pt",
        "name": "Platin",
        "nameEN": "Platinum",
        "summary": "Kim loại quý, dùng làm trang sức, xúc tác.",
        "x": 10,
        "y": 6,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "195.084",
        "density": 21.46,
        "meltingPoint": 2041.4,
        "boilingPoint": 4098,
        "yearDiscovered": "1735"
    },
    "Au": {
        "number": 79,
        "symbol": "Au",
        "name": "Vàng",
        "nameEN": "Gold",
        "summary": "Kim loại quý, dùng làm trang sức, tiền tệ.",
        "x": 11,
        "y": 6,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "196.967",
        "density": 19.3,
        "meltingPoint": 1337.33,
        "boilingPoint": 3129,
        "yearDiscovered": "Cổ đại"
    },
    "Hg": {
        "number": 80,
        "symbol": "Hg",
        "name": "Thủy ngân",
        "nameEN": "Mercury",
        "summary": "Kim loại lỏng ở nhiệt độ phòng, độc.",
        "x": 12,
        "y": 6,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "200.592",
        "density": 13.5336,
        "meltingPoint": 234.321,
        "boilingPoint": 629.88,
        "yearDiscovered": "Cổ đại"
    },
    "Tl": {
        "number": 81,
        "symbol": "Tl",
        "name": "Thalli",
        "nameEN": "Thallium",
        "summary": "Kim loại yếu, rất độc.",
        "x": 13,
        "y": 6,
        "categoryClass": "post-transition-metal",
        "modelSrc": null,
        "atomicMass": "204.38",
        "density": 11.85,
        "meltingPoint": 577,
        "boilingPoint": 1746,
        "yearDiscovered": "1861"
    },
    "Pb": {
        "number": 82,
        "symbol": "Pb",
        "name": "Chì",
        "nameEN": "Lead",
        "summary": "Kim loại yếu, độc, dùng trong ắc quy.",
        "x": 14,
        "y": 6,
        "categoryClass": "post-transition-metal",
        "modelSrc": null,
        "atomicMass": "207.2",
        "density": 11.342,
        "meltingPoint": 600.61,
        "boilingPoint": 2022,
        "yearDiscovered": "Cổ đại"
    },
    "Bi": {
        "number": 83,
        "symbol": "Bi",
        "name": "Bismuth",
        "nameEN": "Bismuth",
        "summary": "Kim loại yếu, dùng trong y tế, hợp kim.",
        "x": 15,
        "y": 6,
        "categoryClass": "post-transition-metal",
        "modelSrc": null,
        "atomicMass": "208.980",
        "density": 9.807,
        "meltingPoint": 544.7,
        "boilingPoint": 1837,
        "yearDiscovered": "Cổ đại"
    },
    "Po": {
        "number": 84,
        "symbol": "Po",
        "name": "Poloni",
        "nameEN": "Polonium",
        "summary": "Á kim, phóng xạ cực mạnh.",
        "x": 16,
        "y": 6,
        "categoryClass": "post-transition-metal",
        "modelSrc": null,
        "atomicMass": "(209)",
        "density": 9.32,
        "meltingPoint": 527,
        "boilingPoint": 1235,
        "yearDiscovered": "1898"
    },
    "At": {
        "number": 85,
        "symbol": "At",
        "name": "Astatin",
        "nameEN": "Astatine",
        "summary": "Halogen phóng xạ, hiếm nhất trên Trái Đất.",
        "x": 17,
        "y": 6,
        "categoryClass": "metalloid",
        "modelSrc": null,
        "atomicMass": "(210)",
        "density": null,
        "meltingPoint": 575,
        "boilingPoint": 610,
        "yearDiscovered": "1940"
    },
    "Rn": {
        "number": 86,
        "symbol": "Rn",
        "name": "Radon",
        "nameEN": "Radon",
        "summary": "Khí hiếm phóng xạ, gây ung thư phổi.",
        "x": 18,
        "y": 6,
        "categoryClass": "noble-gas",
        "modelSrc": null,
        "atomicMass": "(222)",
        "density": 0.00973,
        "meltingPoint": 202,
        "boilingPoint": 211.5,
        "yearDiscovered": "1900"
    },
    "Fr": {
        "number": 87,
        "symbol": "Fr",
        "name": "Franci",
        "nameEN": "Francium",
        "summary": "Kim loại kiềm phóng xạ, hiếm.",
        "x": 1,
        "y": 7,
        "categoryClass": "alkali-metal",
        "modelSrc": null,
        "atomicMass": "(223)",
        "density": null,
        "meltingPoint": 295,
        "boilingPoint": 950,
        "yearDiscovered": "1939"
    },
    "Ra": {
        "number": 88,
        "symbol": "Ra",
        "name": "Radi",
        "nameEN": "Radium",
        "summary": "Kim loại kiềm thổ, phóng xạ, phát quang.",
        "x": 2,
        "y": 7,
        "categoryClass": "alkaline-earth-metal",
        "modelSrc": null,
        "atomicMass": "(226)",
        "density": 5.5,
        "meltingPoint": 973,
        "boilingPoint": 2010,
        "yearDiscovered": "1898"
    },
    "Ac": {
        "number": 89,
        "symbol": "Ac",
        "name": "Actini",
        "nameEN": "Actinium",
        "summary": "Nguyên tố đầu tiên của nhóm Actini.",
        "x": 3,
        "y": 7,
        "categoryClass": "actinide",
        "modelSrc": null,
        "atomicMass": "(227)",
        "density": 10.07,
        "meltingPoint": 1323,
        "boilingPoint": 3471,
        "yearDiscovered": "1899"
    },
    "Rf": {
        "number": 104,
        "symbol": "Rf",
        "name": "Rutherfordi",
        "nameEN": "Rutherfordium",
        "summary": "Nguyên tố siêu nặng, tổng hợp.",
        "x": 4,
        "y": 7,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "(267)",
        "density": null,
        "meltingPoint": null,
        "boilingPoint": null,
        "yearDiscovered": "1964"
    },
    "Db": {
        "number": 105,
        "symbol": "Db",
        "name": "Dubni",
        "nameEN": "Dubnium",
        "summary": "Nguyên tố siêu nặng, tổng hợp.",
        "x": 5,
        "y": 7,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "(270)",
        "density": null,
        "meltingPoint": null,
        "boilingPoint": null,
        "yearDiscovered": "1967"
    },
    "Sg": {
        "number": 106,
        "symbol": "Sg",
        "name": "Seaborgi",
        "nameEN": "Seaborgium",
        "summary": "Nguyên tố siêu nặng, tổng hợp.",
        "x": 6,
        "y": 7,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "(271)",
        "density": null,
        "meltingPoint": null,
        "boilingPoint": null,
        "yearDiscovered": "1974"
    },
    "Bh": {
        "number": 107,
        "symbol": "Bh",
        "name": "Bohri",
        "nameEN": "Bohrium",
        "summary": "Nguyên tố siêu nặng, tổng hợp.",
        "x": 7,
        "y": 7,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "(270)",
        "density": null,
        "meltingPoint": null,
        "boilingPoint": null,
        "yearDiscovered": "1981"
    },
    "Hs": {
        "number": 108,
        "symbol": "Hs",
        "name": "Hassi",
        "nameEN": "Hassium",
        "summary": "Nguyên tố siêu nặng, tổng hợp.",
        "x": 8,
        "y": 7,
        "categoryClass": "transition-metal",
        "modelSrc": null,
        "atomicMass": "(277)",
        "density": null,
        "meltingPoint": null,
        "boilingPoint": null,
        "yearDiscovered": "1984"
    },
    "Mt": {
        "number": 109,
        "symbol": "Mt",
        "name": "Meitneri",
        "nameEN": "Meitnerium",
        "summary": "Nguyên tố siêu nặng, tổng hợp.",
        "x": 9,
        "y": 7,
        "categoryClass": "unknown",
        "modelSrc": null,
        "atomicMass": "(278)",
        "density": null,
        "meltingPoint": null,
        "boilingPoint": null,
        "yearDiscovered": "1982"
    },
    "Ds": {
        "number": 110,
        "symbol": "Ds",
        "name": "Darmstadti",
        "nameEN": "Darmstadtium",
        "summary": "Nguyên tố siêu nặng, tổng hợp.",
        "x": 10,
        "y": 7,
        "categoryClass": "unknown",
        "modelSrc": null,
        "atomicMass": "(281)",
        "density": null,
        "meltingPoint": null,
        "boilingPoint": null,
        "yearDiscovered": "1994"
    },
    "Rg": {
        "number": 111,
        "symbol": "Rg",
        "name": "Roentgeni",
        "nameEN": "Roentgenium",
        "summary": "Nguyên tố siêu nặng, tổng hợp.",
        "x": 11,
        "y": 7,
        "categoryClass": "unknown",
        "modelSrc": null,
        "atomicMass": "(282)",
        "density": null,
        "meltingPoint": null,
        "boilingPoint": null,
        "yearDiscovered": "1994"
    },
    "Cn": {
        "number": 112,
        "symbol": "Cn",
        "name": "Copernici",
        "nameEN": "Copernicium",
        "summary": "Nguyên tố siêu nặng, tổng hợp.",
        "x": 12,
        "y": 7,
        "categoryClass": "unknown",
        "modelSrc": null,
        "atomicMass": "(285)",
        "density": null,
        "meltingPoint": null,
        "boilingPoint": 357,
        "yearDiscovered": "1996"
    },
    "Nh": {
        "number": 113,
        "symbol": "Nh",
        "name": "Nihoni",
        "nameEN": "Nihonium",
        "summary": "Nguyên tố siêu nặng, tổng hợp.",
        "x": 13,
        "y": 7,
        "categoryClass": "unknown",
        "modelSrc": null,
        "atomicMass": "(286)",
        "density": null,
        "meltingPoint": null,
        "boilingPoint": null,
        "yearDiscovered": "2004"
    },
    "Fl": {
        "number": 114,
        "symbol": "Fl",
        "name": "Flerovi",
        "nameEN": "Flerovium",
        "summary": "Nguyên tố siêu nặng, tổng hợp.",
        "x": 14,
        "y": 7,
        "categoryClass": "unknown",
        "modelSrc": null,
        "atomicMass": "(289)",
        "density": null,
        "meltingPoint": null,
        "boilingPoint": 200,
        "yearDiscovered": "1999"
    },
    "Mc": {
        "number": 115,
        "symbol": "Mc",
        "name": "Moscovi",
        "nameEN": "Moscovium",
        "summary": "Nguyên tố siêu nặng, tổng hợp.",
        "x": 15,
        "y": 7,
        "categoryClass": "unknown",
        "modelSrc": null,
        "atomicMass": "(290)",
        "density": null,
        "meltingPoint": null,
        "boilingPoint": null,
        "yearDiscovered": "2003"
    },
    "Lv": {
        "number": 116,
        "symbol": "Lv",
        "name": "Livermori",
        "nameEN": "Livermorium",
        "summary": "Nguyên tố siêu nặng, tổng hợp.",
        "x": 16,
        "y": 7,
        "categoryClass": "unknown",
        "modelSrc": null,
        "atomicMass": "(293)",
        "density": null,
        "meltingPoint": null,
        "boilingPoint": null,
        "yearDiscovered": "2000"
    },
    "Ts": {
        "number": 117,
        "symbol": "Ts",
        "name": "Tennessine",
        "nameEN": "Tennessine",
        "summary": "Nguyên tố siêu nặng, tổng hợp.",
        "x": 17,
        "y": 7,
        "categoryClass": "unknown",
        "modelSrc": null,
        "atomicMass": "(294)",
        "density": null,
        "meltingPoint": null,
        "boilingPoint": null,
        "yearDiscovered": "2010"
    },
    "Og": {
        "number": 118,
        "symbol": "Og",
        "name": "Oganesson",
        "nameEN": "Oganesson",
        "summary": "Nguyên tố siêu nặng, tổng hợp.",
        "x": 18,
        "y": 7,
        "categoryClass": "unknown",
        "modelSrc": null,
        "atomicMass": "(294)",
        "density": null,
        "meltingPoint": null,
        "boilingPoint": 350,
        "yearDiscovered": "2006"
    },
    "Ce": {
        "number": 58,
        "symbol": "Ce",
        "name": "Ceri",
        "nameEN": "Cerium",
        "summary": "Kim loại Lanthan, dùng trong đá lửa.",
        "x": 4,
        "y": 9,
        "categoryClass": "lanthanide",
        "modelSrc": null,
        "atomicMass": "140.116",
        "density": 6.77,
        "meltingPoint": 1068,
        "boilingPoint": 3716,
        "yearDiscovered": "1803"
    },
    "Pr": {
        "number": 59,
        "symbol": "Pr",
        "name": "Praseodymi",
        "nameEN": "Praseodymium",
        "summary": "Kim loại Lanthan, dùng trong nam châm.",
        "x": 5,
        "y": 9,
        "categoryClass": "lanthanide",
        "modelSrc": null,
        "atomicMass": "140.908",
        "density": 6.773,
        "meltingPoint": 1208,
        "boilingPoint": 3793,
        "yearDiscovered": "1885"
    },
    "Nd": {
        "number": 60,
        "symbol": "Nd",
        "name": "Neodymi",
        "nameEN": "Neodymium",
        "summary": "Kim loại Lanthan, dùng trong nam châm mạnh.",
        "x": 6,
        "y": 9,
        "categoryClass": "lanthanide",
        "modelSrc": null,
        "atomicMass": "144.242",
        "density": 7.007,
        "meltingPoint": 1297,
        "boilingPoint": 3347,
        "yearDiscovered": "1885"
    },
    "Pm": {
        "number": 61,
        "symbol": "Pm",
        "name": "Promethi",
        "nameEN": "Promethium",
        "summary": "Kim loại Lanthan, phóng xạ.",
        "x": 7,
        "y": 9,
        "categoryClass": "lanthanide",
        "modelSrc": null,
        "atomicMass": "(145)",
        "density": 7.26,
        "meltingPoint": 1315,
        "boilingPoint": 3273,
        "yearDiscovered": "1945"
    },
    "Sm": {
        "number": 62,
        "symbol": "Sm",
        "name": "Samari",
        "nameEN": "Samarium",
        "summary": "Kim loại Lanthan, dùng trong nam châm.",
        "x": 8,
        "y": 9,
        "categoryClass": "lanthanide",
        "modelSrc": null,
        "atomicMass": "150.36",
        "density": 7.52,
        "meltingPoint": 1345,
        "boilingPoint": 2067,
        "yearDiscovered": "1879"
    },
    "Eu": {
        "number": 63,
        "symbol": "Eu",
        "name": "Europi",
        "nameEN": "Europium",
        "summary": "Kim loại Lanthan, dùng trong TV màu (đỏ).",
        "x": 9,
        "y": 9,
        "categoryClass": "lanthanide",
        "modelSrc": null,
        "atomicMass": "151.964",
        "density": 5.243,
        "meltingPoint": 1099,
        "boilingPoint": 1802,
        "yearDiscovered": "1901"
    },
    "Gd": {
        "number": 64,
        "symbol": "Gd",
        "name": "Gadolini",
        "nameEN": "Gadolinium",
        "summary": "Kim loại Lanthan, dùng trong MRI.",
        "x": 10,
        "y": 9,
        "categoryClass": "lanthanide",
        "modelSrc": null,
        "atomicMass": "157.25",
        "density": 7.895,
        "meltingPoint": 1585,
        "boilingPoint": 3546,
        "yearDiscovered": "1880"
    },
    "Tb": {
        "number": 65,
        "symbol": "Tb",
        "name": "Terbi",
        "nameEN": "Terbium",
        "summary": "Kim loại Lanthan, dùng trong đèn huỳnh quang.",
        "x": 11,
        "y": 9,
        "categoryClass": "lanthanide",
        "modelSrc": null,
        "atomicMass": "158.925",
        "density": 8.229,
        "meltingPoint": 1629,
        "boilingPoint": 3503,
        "yearDiscovered": "1843"
    },
    "Dy": {
        "number": 66,
        "symbol": "Dy",
        "name": "Dysprosi",
        "nameEN": "Dysprosium",
        "summary": "Kim loại Lanthan, dùng trong ổ cứng.",
        "x": 12,
        "y": 9,
        "categoryClass": "lanthanide",
        "modelSrc": null,
        "atomicMass": "162.500",
        "density": 8.55,
        "meltingPoint": 1680,
        "boilingPoint": 2840,
        "yearDiscovered": "1886"
    },
    "Ho": {
        "number": 67,
        "symbol": "Ho",
        "name": "Holmi",
        "nameEN": "Holmium",
        "summary": "Kim loại Lanthan, có từ tính cao nhất.",
        "x": 13,
        "y": 9,
        "categoryClass": "lanthanide",
        "modelSrc": null,
        "atomicMass": "164.930",
        "density": 8.795,
        "meltingPoint": 1734,
        "boilingPoint": 2993,
        "yearDiscovered": "1878"
    },
    "Er": {
        "number": 68,
        "symbol": "Er",
        "name": "Erbi",
        "nameEN": "Erbium",
        "summary": "Kim loại Lanthan, dùng trong cáp quang.",
        "x": 14,
        "y": 9,
        "categoryClass": "lanthanide",
        "modelSrc": null,
        "atomicMass": "167.259",
        "density": 9.066,
        "meltingPoint": 1802,
        "boilingPoint": 3141,
        "yearDiscovered": "1843"
    },
    "Tm": {
        "number": 69,
        "symbol": "Tm",
        "name": "Thuli",
        "nameEN": "Thulium",
        "summary": "Kim loại Lanthan, dùng trong laser.",
        "x": 15,
        "y": 9,
        "categoryClass": "lanthanide",
        "modelSrc": null,
        "atomicMass": "168.934",
        "density": 9.321,
        "meltingPoint": 1818,
        "boilingPoint": 2223,
        "yearDiscovered": "1879"
    },
    "Yb": {
        "number": 70,
        "symbol": "Yb",
        "name": "Ytterbi",
        "nameEN": "Ytterbium",
        "summary": "Kim loại Lanthan, dùng trong laser.",
        "x": 16,
        "y": 9,
        "categoryClass": "lanthanide",
        "modelSrc": null,
        "atomicMass": "173.054",
        "density": 6.965,
        "meltingPoint": 1097,
        "boilingPoint": 1469,
        "yearDiscovered": "1878"
    },
    "Lu": {
        "number": 71,
        "symbol": "Lu",
        "name": "Luteti",
        "nameEN": "Lutetium",
        "summary": "Kim loại Lanthan, dùng trong xúc tác.",
        "x": 17,
        "y": 9,
        "categoryClass": "lanthanide",
        "modelSrc": null,
        "atomicMass": "174.967",
        "density": 9.84,
        "meltingPoint": 1925,
        "boilingPoint": 3675,
        "yearDiscovered": "1907"
    },
    "Th": {
        "number": 90,
        "symbol": "Th",
        "name": "Thori",
        "nameEN": "Thorium",
        "summary": "Kim loại Actini, nhiên liệu hạt nhân.",
        "x": 4,
        "y": 10,
        "categoryClass": "actinide",
        "modelSrc": null,
        "atomicMass": "232.038",
        "density": 11.724,
        "meltingPoint": 2023,
        "boilingPoint": 5061,
        "yearDiscovered": "1829"
    },
    "Pa": {
        "number": 91,
        "symbol": "Pa",
        "name": "Protactini",
        "nameEN": "Protactinium",
        "summary": "Kim loại Actini, phóng xạ.",
        "x": 5,
        "y": 10,
        "categoryClass": "actinide",
        "modelSrc": null,
        "atomicMass": "231.036",
        "density": 15.37,
        "meltingPoint": 1841,
        "boilingPoint": 4300,
        "yearDiscovered": "1913"
    },
    "U": {
        "number": 92,
        "symbol": "U",
        "name": "Urani",
        "nameEN": "Uranium",
        "summary": "Kim loại Actini, nhiên liệu hạt nhân chính.",
        "x": 6,
        "y": 10,
        "categoryClass": "actinide",
        "modelSrc": null,
        "atomicMass": "238.029",
        "density": 18.95,
        "meltingPoint": 1405.3,
        "boilingPoint": 4404,
        "yearDiscovered": "1789"
    },
    "Np": {
        "number": 93,
        "symbol": "Np",
        "name": "Neptuni",
        "nameEN": "Neptunium",
        "summary": "Kim loại Actini, tổng hợp.",
        "x": 7,
        "y": 10,
        "categoryClass": "actinide",
        "modelSrc": null,
        "atomicMass": "(237)",
        "density": 20.45,
        "meltingPoint": 917,
        "boilingPoint": 4273,
        "yearDiscovered": "1940"
    },
    "Pu": {
        "number": 94,
        "symbol": "Pu",
        "name": "Plutoni",
        "nameEN": "Plutonium",
        "summary": "Kim loại Actini, dùng trong vũ khí hạt nhân.",
        "x": 8,
        "y": 10,
        "categoryClass": "actinide",
        "modelSrc": null,
        "atomicMass": "(244)",
        "density": 19.84,
        "meltingPoint": 912.5,
        "boilingPoint": 3501,
        "yearDiscovered": "1940"
    },
    "Am": {
        "number": 95,
        "symbol": "Am",
        "name": "Americi",
        "nameEN": "Americium",
        "summary": "Kim loại Actini, dùng trong báo khói.",
        "x": 9,
        "y": 10,
        "categoryClass": "actinide",
        "modelSrc": null,
        "atomicMass": "(243)",
        "density": 13.69,
        "meltingPoint": 1449,
        "boilingPoint": 2880,
        "yearDiscovered": "1944"
    },
    "Cm": {
        "number": 96,
        "symbol": "Cm",
        "name": "Curi",
        "nameEN": "Curium",
        "summary": "Kim loại Actini, tổng hợp.",
        "x": 10,
        "y": 10,
        "categoryClass": "actinide",
        "modelSrc": null,
        "atomicMass": "(247)",
        "density": 13.51,
        "meltingPoint": 1613,
        "boilingPoint": 3383,
        "yearDiscovered": "1944"
    },
    "Bk": {
        "number": 97,
        "symbol": "Bk",
        "name": "Berkeli",
        "nameEN": "Berkelium",
        "summary": "Kim loại Actini, tổng hợp.",
        "x": 11,
        "y": 10,
        "categoryClass": "actinide",
        "modelSrc": null,
        "atomicMass": "(247)",
        "density": 14.79,
        "meltingPoint": 1259,
        "boilingPoint": 2900,
        "yearDiscovered": "1949"
    },
    "Cf": {
        "number": 98,
        "symbol": "Cf",
        "name": "Californi",
        "nameEN": "Californium",
        "summary": "Kim loại Actini, tổng hợp.",
        "x": 12,
        "y": 10,
        "categoryClass": "actinide",
        "modelSrc": null,
        "atomicMass": "(251)",
        "density": 15.1,
        "meltingPoint": 1173,
        "boilingPoint": 1743,
        "yearDiscovered": "1950"
    },
    "Es": {
        "number": 99,
        "symbol": "Es",
        "name": "Einsteini",
        "nameEN": "Einsteinium",
        "summary": "Kim loại Actini, tổng hợp.",
        "x": 13,
        "y": 10,
        "categoryClass": "actinide",
        "modelSrc": null,
        "atomicMass": "(252)",
        "density": 8.84,
        "meltingPoint": 1133,
        "boilingPoint": 1269,
        "yearDiscovered": "1952"
    },
    "Fm": {
        "number": 100,
        "symbol": "Fm",
        "name": "Fermi",
        "nameEN": "Fermium",
        "summary": "Kim loại Actini, tổng hợp.",
        "x": 14,
        "y": 10,
        "categoryClass": "actinide",
        "modelSrc": null,
        "atomicMass": "(257)",
        "density": null,
        "meltingPoint": 1800,
        "boilingPoint": null,
        "yearDiscovered": "1952"
    },
    "Md": {
        "number": 101,
        "symbol": "Md",
        "name": "Mendelevi",
        "nameEN": "Mendelevium",
        "summary": "Kim loại Actini, tổng hợp.",
        "x": 15,
        "y": 10,
        "categoryClass": "actinide",
        "modelSrc": null,
        "atomicMass": "(258)",
        "density": null,
        "meltingPoint": 1100,
        "boilingPoint": null,
        "yearDiscovered": "1955"
    },
    "No": {
        "number": 102,
        "symbol": "No",
        "name": "Nobeli",
        "nameEN": "Nobelium",
        "summary": "Kim loại Actini, tổng hợp.",
        "x": 16,
        "y": 10,
        "categoryClass": "actinide",
        "modelSrc": null,
        "atomicMass": "(259)",
        "density": null,
        "meltingPoint": 1100,
        "boilingPoint": null,
        "yearDiscovered": "1958"
    },
    "Lr": {
        "number": 103,
        "symbol": "Lr",
        "name": "Lawrenci",
        "nameEN": "Lawrencium",
        "summary": "Kim loại Actini, tổng hợp.",
        "x": 17,
        "y": 10,
        "categoryClass": "actinide",
        "modelSrc": null,
        "atomicMass": "(262)",
        "density": null,
        "meltingPoint": 1900,
        "boilingPoint": null,
        "yearDiscovered": "1961"
    }
}
